### ISSUE TITLE
godot3.4 && godot4.0

### ISSUE THREAD

**Issue by scgm0** [Geequlim/ECMAScript#117] opened 2022-02-24 04:23 UTC
I really like godot and javascript.
But the latest supported version seems to be stuck at godot3.3. (My own attempt at compiling godot 3.4 failed.)
godot4.0 has been tested for alpha, so when will godot3.4 and godot4.0 be supported?
And compiling it yourself is really too painful. . .

I'm not good at English, so I used google translate.

**Comment by Geequlim** [comment] 2022-04-09 07:07
Sorry I can't find time to port this to godot 4.x in the near futuer.
Thanks to @zw7u9tru it works with godot 3.4 nowc!

**Comment by Geequlim** [comment] 2022-04-09 07:08
Sorry I can't find time to port this to godot 4.x in the near futuer.
Thanks to @zw7u9tru it works with godot 3.4 nowc!

**Comment by Geequlim** [comment] 2022-04-09 07:08
Sorry I can't find time to port this to godot 4.x in the near futuer.
Thanks to @zw7u9tru it works with godot 3.4 nowc!

**Comment by scgm0** [comment] 2022-04-09 07:12
> 很抱歉，我找不到时间将其移植到附近的futuer中的godot 4.x。感谢@zw7u9tru它与godot 3.4 nowc一起工作！

好耶

**Comment by fire** [comment] 2023-06-17 01:17
Duplicate of https://github.com/Geequlim/ECMAScript/issues/151

**Closed by fire** 2023-06-17 01:17 UTC
