### ISSUE TITLE
Godot 4.0 Branch

### ISSUE THREAD

**Issue by Flux159** [Geequlim/ECMAScript#35] opened 2020-07-21 04:38 UTC
Hi, thanks for the great module getting JS support in Godot! I was wondering if you were looking at supporting Godot 4.0 in a separate branch.

Godot 4.0 (currently pre-alpha / in development on master branch of godot repository) has a number of breaking API changes, I was experimenting with some of these changes in https://github.com/Flux159/ECMAScript/tree/godot_4.0, but ran into some issues with how Packed<X>Arrays were being used differently from Pooled<X>Arrays along with a number of other C++ errors during compilation.

**Comment by Geequlim** [comment] 2020-07-21 05:52
I'm still waiting godot 4.0 to reach beta or RC status.

**Comment by fire** [comment] 2023-06-17 01:17
Duplicate of https://github.com/Geequlim/ECMAScript/issues/151

**Comment by fire** [comment] 2023-10-01 14:37
Closing after merge https://github.com/Geequlim/ECMAScript/commit/9a3cd3fe74ebb2dcc26ad496c55a8ae3db9cfe4b

**Closed by fire** 2023-10-01 14:37 UTC
Labels: enhancement
